// website-new/src/lib/Footer.svelte
<footer class="bg-black text-white flex justify-between items-center p-5 text-4xl">
    <div class="flex-1 text-left ml-10 tracking-wider">
        CONTACT US FOR ANY QUESTIONS!
    </div>
    <div class="flex-1 text-center hover:brightness-50 transition-all duration-200 tracking-wider">
        <a href="mailto:contact@fbforyou.com" class="text-white no-underline">contact@fbforyou.com</a>
    </div>
    <div class="flex-1 text-right hover:brightness-50 transition-all duration-200 mr-10 tracking-wider">
        <a href="tel:+31061234567" class="text-white no-underline">+31 06 12345678</a>
    </div>
</footer>

// vue-website/src/components/Footer.vue
<template>
    <footer class="bg-black text-white flex justify-between items-center p-5 text-4xl">
        <div class="flex-1 text-left ml-10 tracking-wider">
            CONTACT US FOR ANY QUESTIONS!
        </div>
        <div class="flex-1 text-center hover:brightness-50 transition-all duration-200 tracking-wider">
            <a href="mailto:contact@fbforyou.com" class="text-white no-underline">contact@fbforyou.com</a>
        </div>
        <div class="flex-1 text-right hover:brightness-50 transition-all duration-200 mr-10 tracking-wider">
            <a href="tel:+31061234567" class="text-white no-underline">+31 06 12345678</a>
        </div>
    </footer>
</template>
